version: '3'
services:
  postgresdb: 
    image: postgres
    ports: 
     - 5432:5432
    environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=admin
     - POSTGRES_DB=weather_db
    volumes:
     - ./initdb:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    ports:
     - 80:80
    depends_on:
      - postgresdb
    environment:
     - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
     - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
     - ./pgadmin/servers.json:/pgadmin4/servers.json

  app:
    image: jaroslav2324/vislab_test_weather_backend:latest
    ports:
      - 82:82
    depends_on:
      - postgresdb